### PR TITLE
Add faktory formula

### PR DESCRIPTION
**Pull request by andrewstucki**
Here you go, works like a charm, just `brew tap contribsys/homebrew-faktory && brew install faktory`.

### CODE REVIEW

**Comment by mperham** [comment]
Ok, guess I got the name wrong.  Should I rename this repo to homebrew?

**Comment by andrewstucki** [comment]
nope, doesn't matter

**Comment by andrewstucki** [comment]
Also looks like you read the docs better than I did -- guess homebrew automatically strips the `homebrew-` prefix. So either `brew tap contribsys/faktory` or `brew tap contribsys/homebrew-faktory` work.

**Comment by mperham** [comment]
great, wanted to make sure I wasn't imagining things.  :-)

**Pull request merged**
